package main.endpoints

import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

@RestController
class CreateRoom {
    // todo, create database entry, todo later: encrypt entry based on key generated by client
    @RequestMapping("/createRoom")
    fun createRoom(): String {

        return "room created"
    }
}